lib/admin_to_web/router.ex
defmodule AdminToWeb.Router do
  use AdminToWeb, :router

  import AdminToWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AdminToWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  # Block for custom pipeline

  pipeline :browser_static do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Block for custom routes

  scope "/", AdminToWeb do
    pipe_through :browser_static

    get "/", LandingController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", AdminToWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AdminToWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", AdminToWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  # Block for custom routes

  scope "/", AdminToWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/home", PageLive, :index
    live "/search", SearchLive
  end

  ## Authentication routes

  scope "/", AdminToWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", AdminToWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/admin_to_web/views/layout_view.ex
defmodule AdminToWeb.LayoutView do
  use AdminToWeb, :view
end

lib/admin_to_web/templates/layout/_user_menu.html.eex
<ul>
<%= if @current_user do %>
  <li><%= @current_user.email %></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% end %>
</ul>

lib/admin_to_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/admin_to_web/templates/layout/landing.html.eex
<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "AdminTo", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/landing.css") %>"/>
  </head>
  <body>

    <header>
      <nav class="navbar has-shadow is-fixed-top is-transparent" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="#">
            <img src="<%= Routes.static_path(@conn, "/images/logo_blue.png") %>" alt="#"/>
          </a>

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div class="navbar-menu">
            <div class="navbar-start">
              <a class="navbar-item is-size-4 is-uppercase has-text-weight-medium" href="#">sitename</a>
            </div>
            <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <%= if @current_user do %>
                  <%= link "Back to app", to: Routes.page_path(@conn, :index), class: "button" %>
                <% else %>
                <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "button is-link is-outlined mr-5" %>
                <%= link "Sign in", to: Routes.user_registration_path(@conn, :new), class: "button is-link is-light" %>
                <% end %>
              </div>
            </div>
            </div>
        </div>
      </nav>
    </header>

    <%= @inner_content %>
  </body>
</html>

lib/admin_to_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/admin_to_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "AdminTo", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
          <%= render "_user_menu.html", assigns %>
        </nav>
        <a href="#">
          <img src="<%= Routes.static_path(@conn, "/images/logo_blue.png") %>" alt="#" width="29.82" height="27.98" />
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>